// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Configuration and CLI shared verbatim by the server (service creator) and the
//! client (service opener) binaries.
//!
//! The two processes rendezvous purely through matching *inputs*: an identical
//! [`secured_config()`] and the same `--service-name`/`--pattern`. The IAM
//! endpoint name is derived deterministically from the service hash (which is a
//! function of the service name, messaging pattern and config) plus
//! `iam.endpoint_base`, so identical config + service name + pattern ⇒ both
//! processes resolve to the exact same Unix-domain-socket IAM endpoint.

use clap::{Parser, ValueEnum};
use iceoryx2::config::Config;
use iceoryx2::prelude::{Path, SemanticString};
use iceoryx2_cal::security::mode::SecurityMode;

/// The messaging pattern to exercise. MUST be passed identically to both
/// processes (it feeds into the service hash and therefore the IAM endpoint).
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum Pattern {
    /// Fixed-size publish-subscribe (`u64`). Static data segment.
    Pubsub,
    /// Variable-length publish-subscribe (`[u8]`, `PowerOfTwo` strategy).
    /// Exercises the resizable data segment: management segment + initial
    /// segment (id 0) brokered by IAM handle.
    SlicePubsub,
    /// Request-response (`u64` -> `u64`). Both ports are producer AND consumer,
    /// so IAM-brokered fd passing happens in both directions.
    Reqres,
    /// Event notification.
    Event,
}

/// Shared CLI. Both binaries parse the exact same arguments; only their *role*
/// (creator vs opener) differs, which is fixed by which binary is running.
#[derive(Debug, Parser)]
pub struct Cli {
    /// Service name. Generated by the parent harness and passed to both children.
    #[arg(long)]
    pub service_name: String,

    /// Messaging pattern to exercise.
    #[arg(long, value_enum)]
    pub pattern: Pattern,

    /// Optional iceoryx2 root path (for per-run CI isolation). When set it MUST
    /// be identical for both processes and the directory MUST already exist.
    #[arg(long)]
    pub root_path: Option<String>,

    /// Payload value moved across the boundary (pub-sub / req-resp / event id).
    #[arg(long, default_value_t = 4711)]
    pub value: u64,
}

/// Builds the `SecurityMode::Secured` config. This is the single source of
/// truth both binaries call so they land on the same IAM endpoint. Copied in
/// shape from `iceoryx2/tests/secured_ipc_e2e_tests.rs`.
pub fn secured_config(root_path: Option<&str>) -> Config {
    let mut config = Config::default();
    config.global.node.security.mode = SecurityMode::Secured;
    if let Some(rp) = root_path {
        let path = Path::new(rp.as_bytes()).expect("root_path must be a valid path");
        config.global.set_root_path(&path);
    }
    config
}
